
import ClientLayout from "./components/ClientLayout";

export const metadata = {
  title: "Convex Energy",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ClientLayout>{children}</ClientLayout>
      </body>
    </html>
  );
}